config/routes.rb
Rails.application.routes.draw do


  get 'documents/index'
  get 'documents/new'
  get 'documents/create'
  get 'documents/destroy'
  devise_for :users
  resources :users, only: [:show]

  # mount ActionCable.server => '/cable'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :courses do
    resources :bookings
    resources :reviews
  end

  resources :chats, only: [:show, :index, :create] do
     resources :messages, only: [:index, :create]
  end

  get "/current_index", to: "courses#current_index"
  get "/add_teacher", to: "courses#add_teacher"
  get "/bookings/current_index", to: "bookings#current_index"
  get "/teacher", to: "pages#teacher"
  get "/profile", to: "pages#profile"


  post "/current_locations", to: "pages#user_location"
end

app/views/shared/_banner.html.erb
<div class="banner" style="background: linear-gradient(-225deg, rgba(00,0,0,0.4) 0%, rgba(0,0,0,0.4) 100%), 
    url('https://lh3.googleusercontent.com/unqE6sK2WUscyBwOVwc1CIo6Mq-O_3Td8lf9sVZEU0qnEonf3nTii5h8WevZuqm134_YYqJ1TmEcwr2n4DtNqX6-XbbdlbuuU_HJP4fJn8BmjLCVKmK5h_XMAX8WJbmOY17z2T3uCKxMCJedjjyUHo_S8lnBgBmg4-09OnTz570ph-G_HMJw0PhZMw_xOVj_cogLyIUdqejrt1L7PCSXvaQE7aUplq-GK6VA4id1EfAOxa76-vzEhuo9Y6N7zku3lONx2et-wtesHDAv0AhTNeoXabDffiI-VyXyQaLCWQ9FPZt2rhpL5r2HL71pkQJLwPX4dMoy89I-QDAX9T0Yp6hkfDhTUeGXtAG_ZN2BXBtBkN1ykZDbCUzyT5Ja-ikiuHLMQjbGutwC7KdTOxep0RuXswt5qo9UylMjOclWU2OUBXhnOCdSuilMEua3Nx55dXgTSKIJH4spfU0pQZfZkgrvHOheg9JIFi8e4Ylf4630DgRin_5h4PxWAEbGCfdTQ5LbABREzk0AX3NsJGi0fGmQaPz4HOg-2BOu3l6RfzKDe9eDOjBcyP4jAzE9JyTsJAJrUaaSnCBuCHMcfvFPxjGuxKik5xyF8eysm5MOONQfAqkhZ-PvTxEh89URdCS6RcJN9d9CmHDgf-ZFsk8bIoKnL9xnaivs=w1205-h803-no'); "
  >
  <div class="banner-content">
	    <h1>< Find your private tutor ></h1>
    <form class="home-form" action="/courses" method="get">

      <%= image_tag "searchwhite.png", class: "search-icon" %>
	<input class="searchbox" type="text" name="search" id="search-text" placeholder="JavaScript" autocomplete="off">


  <!-- <i class= "fas fa-search"></i> -->
      <button class="searchbutton", type="button", value="search"></button>
    </form>
    <br> <br>

    <br>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <!-- <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> by CODE_PLUG
  </div> -->
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <!-- <%= link_to root_path, class: "navbar-wagon-brand" do %> -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.svg" %>
  <% end %>
  <!-- <% end %> -->

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <% if current_user.teacher %>
        <%= link_to "List a New Course", new_course_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% else %>
        <%= link_to "Become a Teacher", teacher_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
      <%= link_to "My Courses", current_index_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!--<%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %> -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "/profile" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to chats_path do %>
                <i class="fa fa-envelope"></i>  <%= t(".settings", default: "Messages") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Become a Teacher"), teacher_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <div class="vl"></div>
      <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>