config/routes.rb
Rails.application.routes.draw do


  get 'documents/index'
  get 'documents/new'
  get 'documents/create'
  get 'documents/destroy'
  devise_for :users
  resources :users, only: [:show]

  # mount ActionCable.server => '/cable'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :courses do
    resources :bookings
    resources :reviews
  end

  resources :chats, only: [:show, :index, :create] do
     resources :messages, only: [:index, :create]
  end

  get "/current_index", to: "courses#current_index"
  get "/add_teacher", to: "courses#add_teacher"
  get "/bookings/current_index", to: "bookings#current_index"
  get "/teacher", to: "pages#teacher"
  get "/profile", to: "pages#profile"


  post "/current_locations", to: "pages#user_location"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def current_index
    @courses = policy_scope(Course).order(created_at: :desc)
  end

  def index
    # byebug
    @subjects = Subject.all
    @courses = policy_scope(Course)
    # @courses = policy_scope(Course).limit(1)
    @courses = @courses.where.not(latitude: nil, longitude: nil)

    if params[:search]
      subject_from_search = Subject.where('lower(category) = ?', params[:search].downcase).first
      params[:subject_id] = subject_from_search.id if subject_from_search
    end

    if params[:subject_id]
      @courses = @courses.where(subject_id: params[:subject_id])
    end


# ["0-20€", 1], ["21-50€", 2], ["51€<", 3] PRICE
# ["0-5km", 1], ["6-10km", 2], ["10km<", 3 DISTANCE

    if params[:price]
      if params[:price] == "1"
        @courses = @courses.where("price > ? AND price < ?", 0, 20)
      elsif params[:price] == "2"
        @courses = @courses.where("price > ? AND price < ?", 21, 50)
      elsif params[:price] == "3"
        @courses = @courses.where("price > ?", 51)
      end
    end

    unless current_user.location.nil?
     coords = current_user.location.split("-")
     loc = []
     coords.each do |coord|
      coord = coord.to_f
      loc<< coord
     end
    end



    # DISTANCE to where?

    # if params[:distance]
    #   if params[:distance] == "1"
    #     @courses = @courses.where()
    #   elsif params[:distance] == "2"
    #     @courses = @courses.where()
    #   elsif params[:distance] == "3"
    #     @courses = @courses.where()
    #   end
    # end

    @filtered_courses = Course.near(loc, params[:distance].to_i)


    # @courses = Course.search_by_city_and_address(params[:subject])
    # @courses = policy_scope(Course).limit(3)

    @markers = @courses.map do |course|
      {
        lat: course.latitude,
        lng: course.longitude
      }
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @course = Course.find(params[:id])
    @booking = Booking.new
      # @markers = { lat: @course.latitude, lng: @course.longitude }
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @subject = Subject.find_by(category: params[:course][:subject])
    @video = course_params[:video].split("=").last
    @course = Course.new(
      subject_id: @subject.id,
      video: @video,
      user: current_user,
      title: course_params[:title],
      price: course_params[:price],
      rate: course_params[:rate],
      description: course_params[:description],
      address: course_params[:address],
      city: course_params[:city],
      photo: course_params[:photo],
      learning: course_params[:learning],
      requirement: course_params[:requirement],
      vimeo_file: course_params[:vimeo_file],
      document_1: course_params[:document_1],
      document_2: course_params[:document_2],
      document_3: course_params[:document_3]
    )

    if @course.save
      redirect_to course_path(@course)
    else
      raise
      render :new
    end
  end

  def update
    if @course.update(course_params)
      redirect_to course_path(@course)
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to current_index_path, notice: 'course was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  def set_course
    @course = Course.find(params[:id])
    authorize @course
  end


  def course_params
    params.require(:course).permit(:video_url, :video, :vimeo_file, :title, :user_id, :price, :description, :address, :city, :photo, :document_1, :document_1_cache, :requirement, :learning, :subject, :photo_cache, :document_2, :document_2_cache, :document_3, :document_3_cache)

  end
end

app/views/courses/_filter.html.erb
<style>
  .flex-container {
    display: flex;
  }
  .flex {
    margin: 15px;
  }
</style>


      <div class="flex-container filter-container">
        <div class="flex-item">
          <%= form_tag(courses_path, remote: true, method: :get) do %>

            <%= select_tag "subject_id", options_from_collection_for_select(@subjects, "id", "category", params[:subject_id]) %>

            <%= select_tag "price", options_for_select([["Any", nil], ["0-20€", 1], ["21-50€", 2], ["51€<", 3] ], params[:price])%>

            <%= select_tag "distance", options_for_select([["Any", nil], ["0-5km", 5], ["6-10km", 10], ["10km<", 15] ], params[:distance])%>

            <%= submit_tag :submit, class: "btn-filter", value:"Search" %>
          <% end %>
        </div>
      </div>

app/views/courses/_form.html.erb
<div class="container" style="margin-top: 3vh;">
  <div class="row">
    <h1 style="margin-bottom: 3vh;">Design your own course - be creative :</h1> <br> <br>
    <div class="col-md-8">

      <%= simple_form_for(@course) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :title , as: :string, label: "Please indicate the name of the course you are teaching, e.g. 'Ruby on Rails' ", placeholder: "Name of the course" %> <br> <br>
        <%= f.input :description, class: "effect-4", label: "Please make a detailed description on the course, stating what it is about and how it will be organized   ", placeholder: "Course description" %><br>
        <%= f.input :learning, class: "effect-4", label: "Describe what the teacher will know by the end of the course", placeholder: "Describe what the student will learn" %><br>
        <%= f.input :requirement, class: "effect-4", label: "If the student should already know some basics before enrolling in the course, please state here. Otherwise state 'no requirements'", placeholder: "Describe what the student should already know" %><br>
        <%= f.input :price, label: "Indicate what is the price you are requiring for teaching   per hour", placeholder: "Your price per hour" %><br>
        <%= f.input :address, label: "Indicate the current address you would be teaching the student. In case you don't have a specific address, state the city", placeholder: "Where would you teach?"  %><br>

        <%= f.input :city, label: "Indicate in which area in the city you will be teaching", placeholder: "In what area?" %> <br> <br>



        <%= f.input :subject, as: :select, collection: Subject.all.map(&:category) %> <br> <br> <br>
        <%= f.input :video, label: "Insert the URL from the video (youtube)", placeholder: "Youtube video" %> <br> <br>
        <%= f.input :document_1, label: "Import a PDF document"  %>
        <%= f.input :document_1_cache, as: :hidden %>
        <%= f.input :document_2, label: "Import a PDF document"%>
        <%= f.input :document_2_cache, as: :hidden %>
        <%= f.input :document_3, label: "Import a PDF document"%>
        <%= f.input :document_3_cache, as: :hidden %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, class: "btn btn-primary btn-block", value: "Create your Course"%>
      </div>
      <% end %>
    </div>
  </div>
</div>


<!-- <div class="col-3">
          <input class="effect-4" type="text" placeholder="Placeholr Text">
            <span class="focus-border"></span>
        </div>
      -->

app/views/courses/_list.html.erb
<% if @courses.empty? %>
  <h2>We're sorry, but CODE:PLUG does not currently offer any classes in this language.</h2>
<% else %>
  <% @courses.each do |course| %>

    <div class="col-xs-12 col-sm-6">
      <div class="lesson-card">
      <%= link_to '', course_path(course), class: 'lesson-card-link' %>

        <div class="lesson-card-left">
          <img class="lesson-card-avatar" src=<%= !course.photo.url.nil? ? cl_image_path(course.photo) : 'http://res.cloudinary.com/arthurpfister/image/upload/v1528218508/max-nelson-492729-unsplash.jpg' %>>
          <p class="lesson-card-teacher"><%= "#{course.user.first_name} #{course.user.last_name.first}." %></p>
          <p class="lesson-card-rating"><%= '★' * course.rate.to_i %></p>
        </div>

        <div class="lesson-card-right">
          <h5 class="lesson-card-title"><%=course.title %></h5>
          <%= image_tag ApplicationHelper.get_image_name_from_subject(course.subject.category.downcase), class:"lesson-card-badge"%>
          <p class="lesson-card-address"><%= course.address %></p>
          <p class="lesson-card-description"><%= course.description[0,120] %>.. <%= link_to '(Read more)','#', style: 'font-size: 13px' %></p>
          <h6 class="lesson-card-price"><%=course.price%>€/h</h6>
        </div>

      </div>

   </div>
  <% end %>
<% end %>

app/views/courses/_map.html.erb
<div id="map"
    style="width: 100%;"
    data-markers="<%= @markers.to_json %>">
</div>

app/views/courses/_swiper.html.erb
<!-- Slider main container -->
<div class="swiper-container">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
        <!-- Slides -->
        <div class="swiper-slide">Slide 1</div>
        <div class="swiper-slide blue ">Slide 2</div>
        <div class="swiper-slide red">Slide 3</div>
        ...
    </div>
    <!-- If we need pagination -->
    <div class="swiper-pagination"></div>
    
    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
    
    <!-- If we need scrollbar -->
<!--     <div class="swiper-scrollbar"></div> -->
</div>

app/views/courses/current_index.html.erb
<div class="container">
  <div class="row">
    <% @courses.each do |course| %>
      <% if course.user_id == current_user.id %>
        <div class="col-xs-12 col-sm-12 col-md-6">
          <div class="card">
            <% if course.photo.url.nil? %>
              <div class="front">
                <img src="http://res.cloudinary.com/arthurpfister/image/upload/v1528218508/max-nelson-492729-unsplash.jpg" alt="" class="center">
                <div class="caption">
                  <h2><%=course.title %></h2>
                  <h6><%=course.price%>€    per hour</h6><br>
                  <p><%= course.description[0,300] %>...
                    <a href="#"><%= link_to "", course_path(course)%></a>
                </div>
              </div>
            <% else %>
              <div class="front">
                <img src=<%= cl_image_path course.photo %>>
                <div class="caption">
                  <h2><%=course.title %></h2>
                  <h6><%=course.price%>€    per hour</h6><br>
                  <p><%= course.description[0,300] %>...
                    <a href="#"><%= link_to "", course_path(course)%></a>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/courses/index.html.erb
<div class="container-fluid">
  <div class="row">

    <%= render "filter" %>

    <!-- <input type="submit" id="demo" onclick="setCurrentLocation()"> -->



    <div class="col-md-8">


      <div id="courses-list" class="row pull-right">
        <%= render "list" %>




      </div>


    </div>

    <div id="courses-map" class="col-xs-12 col-sm-6 col-md-4">
     <%= render "map" %>
   </div>
 </div>

app/views/courses/index.js.erb
var new_list_html = '<%= j render "list" %>'
var new_map_html = '<%= j render "map" %>'

var newList = document.getElementById('courses-list');
newList.innerHTML = new_list_html;

var newMap = document.getElementById('courses-map');
newMap.innerHTML = new_map_html;

document.loadGoogleMap();

app/views/courses/new.html.erb
<%= render 'form', course: @course %>

app/views/courses/show.html.erb
<style>
.flatpickr-weekdays {
	display: none !important;
}
</style>


<div class="wrapper">
	<div class="container show-container" style="margin-top: 30px !important">
		<div class="row">

<!-- <marquee behavior="" direction="up" bgcolor="turquoise"><h1>My A$$ Fuck</h1></marquee>
<marquee truespeed="20" direction="down" width="600" height="600" behavior="alternate" style="border:solid">
  <marquee behavior="alternate">
    <h2 style="font-size: 40px">WHAT THE ACTUAL FUCK</h2>
  </marquee>
</marquee> -->
<div class="col-sm-3">
	<div class="profile-line">
		<div class="user-card">
			<div class="user-card-left">
				<%= cl_image_tag @course.photo, id: "avatar" %>
			</div>

			<div class="user-card-right">
				<h1 class="break-word"><%= @course.user.first_name %> <%= @course.user.last_name %> </h1>
				<p class="break-word"> <i class="fas fa-phone"></i><%= @course.user.phone_number%></p>
				<p><%= raw '<i class="fas fa-star"></i>' * @course.rate.to_i %></p>
              <div class="talk-teacher-2">
        <%= link_to "Get in touch", chats_path(sender_id: current_user.id, recipient_id: @course.user.id), method: :post, class: "button_2 btn-block" %>
      </div>
			</div>
		</div>

		<div class="teacher-about-me">
			<h4 class="break-word"><%=@course.user.current_position %></h4>
			<p><%=@course.user.description %></p>
		</div>


		<div class="teacher-skills">
			<h4>Coding languages</h4>
			<p>   <%= @course.user.languages %> </p>
		</div>

    <div class="feedback">
		<h4>Teacher feedback</h4>
		<p>(150 reviews)</p>
		<p> Average: <%= '★' * @course.rate.to_i %></p>
  </div>


    <div class="feedback">
      <div class="review">
        <div class="review-name">
          <img class="avatar-small avatar-1" src="https://kitt.lewagon.com/placeholder/users/random">
          <div class="avatar-tooltip tooltip-1">
            <h6 style="font-size: 12px font-weight:bolder margin-bottom:2px;">Marta</h1>
            <p>1 month ago</p>
          </div>
        </div>
        <div class="review-description">
          <h5>Great teacher!</h5>
          <p>The teacher was amazing! He was always available to answer my questions and we worked a lot online as well. The materials and the way he structured the lectures were great.</p>
        </div>
      </div>
    </div>

    <div class="feedback">
      <div class="review">
        <div class="review-name">
          <img class="avatar-small avatar-2" src="https://kitt.lewagon.com/placeholder/users/random">
          <div class="avatar-tooltip tooltip-2">
            <h6 style="font-size: 12px font-weight:bolder margin-bottom:2px;">John</h1>
            <p>1 month ago</p>
          </div>
        </div>
        <div class="review-description">
          <h5>Good Experience!</h5>
          <p>One of the best teachers I have ever had! Always available to help me even outside the schedule time! He provides great materials.</p>
        </div>
      </div>
    </div>

    <div class="feedback">
			<div class="review">
				<div class="review-name">
					<img class="avatar-small avatar-3" src="https://kitt.lewagon.com/placeholder/users/random">
          <div class="avatar-tooltip tooltip-3">
  					<h6 style="font-size: 12px font-weight:bolder margin-bottom:2px;">Peter</h1>
  					<p>1 month ago</p>
          </div>
				</div>
				<div class="review-description">
					<h5>Changed my life!</h5>
					<p>The teacher was really good. I found it really easy to meet his availability and the flexibility he showed was great. I feel like I know a lot about Javascript now!</p>
				</div>
			</div>
		</div>

    <div class="talk-teacher">
			<%= link_to "More reviews", user_path(@course.user), class: "button_3 btn-block" %> </div>


		</div>
	</div>


	<div class="col-xs-12 col-sm-6" style="display: flex">
		<div class="course">
			<div class="row">
				<div class="col-xs-12">
					<div class="course-top" >
						<h1><%= @course.title %>
							<%= image_tag ApplicationHelper.get_image_name_from_subject(@course.subject.category.downcase), class:"image_tag_2"%></h1>
							<p><%= @course.address %> - <%= @course.city %>	</p>
								<h6><%= link_to "(View on google maps)", "https://www.google.com/maps/?q=#{@course.latitude},#{@course.longitude}", target: "_blank" %> </h6>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12">
						<div class="course-video">
							<iframe src="https://www.youtube.com/embed/<%= @course.video %>" height="auto" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12">
						<div class="course-details">
							<h4>Course Description</h4>
							<p><%= @course.description %></p>
							<h4>What will you learn?</h4>
							<p> <%= @course.learning %></p>
							<h4>Requirements</h4>
							<p><%= @course.requirement %></p>
							<h4>Resources</h4>
							<div class="row" style="margin-bottom:30px">
								<div class="resources">
								<div class="col-xs-12 col-md-4">

									<a href="<%= @course.document_1.url %>" target="_blank">

										<%= cl_image_tag(@course.document_1, :width => 200, :height => 250, :crop => :fill, format: "png", class:"box-shadow") %>
									</a>
								</div>
								<div class="col-xs-12 col-md-4">

									<a href="<%= @course.document_2.url %>" target="_blank">

										<%= cl_image_tag(@course.document_2, :width => 200, :height => 250, :crop => :fill, format: "png", class:"box-shadow")  %>
									</a>
								</div>
x								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<%# cl_image_tag @course.photo, height: 250, width: 250, crop: :fill %>

		</div>

		<div class="col-xs-12 col-md-3" style="position: sticky; top: 10px;">

			<div class="book-class">
				<div class="book-menu">
					<h4>Book a class now!</h4>
					<div class="dates">
						<%= simple_form_for [@course, @booking] do |f| %>

  						<div class="col-md-6">
  							<div class="courses-booking-form">
  								<p>Start Date</p>
  								<div class="check_in">
  									<p>
  										<%= f.input :start_date, as: :string, id:'booking_start_date', input_html: { class: 'flatpickr-input' } %>
  									</p>
  								</div>
  							</div>
  						</div>
  						<div class="col-md-6">
  							<p>End Date</p>
  							<div class="check_out">
  								<p>
  									<%= f.input :end_date, as: :string, id:"booking_end_date", input_html: { class: 'flatpickr-input' }  %>
  								</p>

  							</div>
  						</div>
              <%= f.input :hours, as: :hidden %>
  					<p>  <span id="course-price">
  						€<%= @course.price %></span> per hour</p>
  						<div  id="booking-totals" style="display: none;" >
  							<p> Hours booked: <span id="total-hours"></span> hours</p>
  							<p>Total price: <span id="total-price"></span> €</p>
  						</div>
              <%= f.button :submit, value="Book now", class: "button_4 btn-block" %>
	<!-- 			<% end %>



									<div id="calendar">
										<ul class="list-inline">
											<li data-target="mo" class="active-day"><a href="#">MO</a></li>
											<li data-target="tu" ><a href="#">TU</a></li>
											<li data-target="we"><a href="#">WE</a></li>
											<li data-target="th"><a href="#">TH</a></li>
											<li data-target="fr"><a href="#">FR</a></li>
											<li data-target="sa"><a href="#">SA</a></li>
											<li data-target="su"><a href="#">SU</a></li>
										</ul>

										<div id="mo" class="availability active-availability">

											From 9 to 10
										</div>
										<div id="tu" class="availability">

											From 10 to 11
										</div>
										<div id="we" class="availability">					From 12 to 13
										</div>
										<div id="th" class="availability">
											From 14 to 15
										</div>
										<div id="fr" class="availability">
																						F
											From 14 to 15
										</div>
										<div  id="sa" class="availability">	<%= 77 %></div>
										<div id="su"  class="availability">	<%= 88 %></div>
									</div>
								</div> -->

							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>

</div>
</div>

<div class="text-center" style="margin-top: 6vh;">

	<% if policy(@course).destroy? %>
	<%= link_to "Remove this Course", @course, class: "button_2", method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
	<% if policy(@course).edit? %>
	<%= link_to "Edit this Course", edit_course_path(@course), class: "button_2" %>
	<% end %>
	<br>
	<br>
	<br>

</div>




<%= content_for :after_js do %>
  <%= javascript_tag do %>
    document.app.days();
  <% end %>
<% end %>